# LambdaTest Configuration

# Project and folder configuration
project_id: "01KGKPRV93BJZ2FVS1T5AXA36J"
folder_id: "01KGKPY5KSY6X8BFAJEHK2CWZS"
# "01JHFA2G0FGVR1YCG4T2MF4J39"

# Test Run configuration
assignee: 99309
environment_id: 74192

# Test URL for automation
test_url: "https://sireeshakarumanchi.github.io/ai-native-quality-validation-sample/pr-4/"
